#!/bin/bash
outFile=bigNiiPaths
if [ -e $outFile ]; then
	echo "$outFile exists already. Please delete to re-run zipallWrite"
else
	export IFS=$'\n'
	niiList=($(tree --noreport -isfP '*.nii'|grep nii))
	totalNr=${#niiList[@]}
	echo "There are $totalNr nii files"
	nrBigNii=0
	for niiString in "${niiList[@]}"; do
		niiSize=$(echo $niiString|cut -d']' -f 1|sed -e 's/\[//' -e 's/ //g')
		if (( $niiSize > 100000000 )); then
			nrBigNii=$(($nrBigNii + 1))
			niiPath=$(echo $niiString|cut -d']' -f 2)
			echo $niiPath >> $outFile
		fi
	done
	echo "There are $nrBigNii nii files over 100MB"
fi
